title: "Neeraj's Blog"
author: "Neeraj"
domain: neerajkapoor.com
url: https://neerajkapoor.com

theme: pandoc-markdown-jekyll-theme

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-pandoc

markdown: Pandoc
pandoc:
  extensions:
    - from: 'markdown+smart+tex_math_single_backslash'
    - filter: 'pandoc-sidenote'
    - template: '_template'
    - katex
    - toc
    - M: 'site__baseurl=/'
permalink: /:year/:month/:day/:title/
